name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Optionally generate compile_commands.json

    - uses: ZedThree/clang-tidy-review@v0.10.1
      with:
        clang_tidy_checks: '-*,performance-*,bugprone-*,clang-analyzer-*,cppcoreguidelines-*,mpi-*,misc-*,-cppcoreguidelines-avoid-non-const-global-variables,-cppcoreguidelines-avoid-magic-numbers'
        split_workflow: true

    - uses: actions/upload-artifact@v3
      with:
        name: clang-tidy-review
        path: |
          clang-tidy-review-output.json
          clang-tidy-review-metadata.json
